### PR TITLE
Set-buffer instead of current copy mode. Support for upcoming tmux 2.4

### PR DESCRIPTION
**Pull request by fcsonline**
For tmux 2.4, `send-keys` command has changed as you can see here:

https://github.com/tmux/tmux/commit/76d6d3641f271be1756e41494960d96714e7ee58

### CODE REVIEW

**Comment by fcsonline** [comment]
We need to ensure that we don't break older versions.

**Comment by Morantron** [comment]
Renamed the PR, this works in 2.3 but will not work in the next 2.4 version.

**Comment by Morantron** [comment]
I think we could replace all the `actions.sh` file in favour of `tmux set-buffer`, and should be compatible across versions. Although I'm not sure if using this could break the `tmux-yank` integration.

**Comment by fcsonline** [comment]
And I think you can send all those actions in a row.

**Comment by fcsonline** [comment]
What is `tmux-yank` integration?

**Comment by Morantron** [comment]
Merged in `0.5.0` :man_dancing: 

Had to make some changes to make it work with https://github.com/tmux-plugins/tmux-yank ( which provides system clipboard integration )

**Pull request closed without merging**
