### PR TITLE
hinter: use same hint for all occurrences of match

### PR DESCRIPTION
**Pull request by sunaku**
This patch changes the hinter to use the same hint for all occurrences
of a match, thereby reducing the need to use multi-character hints and
also eliminating redundant hints to simplify the user's hint decision.

Before this patch:

<pre>
<b>$</b> awk <b>-f</b></span> <u>scripts/hinter.awk</u> < <u>test/fixtures/ip-output

</u>1: lo: <LOOPBACK,UP,LOWER_UP> mtu <b><span style='color:#A50'>65536</span></b> <b><span style='color:#A50'>[p]</span></b> qdisc noqueue state UNKNOWN group default qlen 1
   <b><span style='color:#A50'> link/loopback</span></b> <b><span style='color:#A50'>[o]</span></b> 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet <b><span style='color:#A50'>127.0.0.1</span></b> <b><span style='color:#A50'>[i]/8</span></b> <b><span style='color:#A50'>[u]</span></b> scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc fq_codel state UP group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 78:31:c1:d5:40:ce brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>192.168.1.33</span></b> <b><span style='color:#A50'>[t]/24</span></b> <b><span style='color:#A50'>[r]</span></b> brd <b><span style='color:#A50'>192.168.1.255</span></b> <b><span style='color:#A50'>[e]</span></b> scope global dynamic wlp3s0
       valid_lft <b><span style='color:#A50'>40162</span></b> <b><span style='color:#A50'>[wj]</span></b>sec preferred_lft <b><span style='color:#A50'>40162</span></b> <b><span style='color:#A50'>[wt]</span></b>sec
    inet6 fe80::7a31:c1ff:fed5:40ce/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
3: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[wr]</span></b> qdisc noqueue state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[we]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[ww]</span></b> 46:06:f6:15:ea:fb brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>10.0.3.1</span></b> <b><span style='color:#A50'>[wq]/24</span></b> <b><span style='color:#A50'>[wf]</span></b> brd <b><span style='color:#A50'>10.0.3.255</span></b> <b><span style='color:#A50'>[wd]</span></b> scope global br0
       valid_lft forever preferred_lft forever
4: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[ws]</span></b> qdisc fq_codel state UP group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[wa]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[qp]</span></b> 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>10.0.1.1</span></b> <b><span style='color:#A50'>[qo]/24</span></b> <b><span style='color:#A50'>[qi]</span></b> brd <b><span style='color:#A50'>10.0.1.255</span></b> <b><span style='color:#A50'>[qu]</span></b> scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet6 fe80::800:27ff:fe00:0/64 scope link
       valid_lft forever preferred_lft forever
5: vboxnet1: <BROADCAST,MULTICAST> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[ql]</span></b> qdisc noop state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[qk]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[qj]</span></b> 0a:00:27:00:00:01 brd ff:ff:ff:ff:ff:ff
6: vboxnet2: <BROADCAST,MULTICAST> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[qt]</span></b> qdisc noop state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[qr]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[qe]</span></b> 0a:00:27:00:00:02 brd ff:ff:ff:ff:ff:ffsh: 1: 3: Bad file descriptor
</pre>

After this patch:

<pre>
<b>$</b> awk <b>-f</b></span> <u>scripts/hinter.awk</u> < <u>test/fixtures/ip-output

</u>1: lo: <LOOPBACK,UP,LOWER_UP> mtu <b><span style='color:#A50'>65536</span></b> <b><span style='color:#A50'>[p]</span></b> qdisc noqueue state UNKNOWN group default qlen 1
   <b><span style='color:#A50'> link/loopback</span></b> <b><span style='color:#A50'>[o]</span></b> 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet <b><span style='color:#A50'>127.0.0.1</span></b> <b><span style='color:#A50'>[i]/8</span></b> <b><span style='color:#A50'>[u]</span></b> scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc fq_codel state UP group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 78:31:c1:d5:40:ce brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>192.168.1.33</span></b> <b><span style='color:#A50'>[t]/24</span></b> <b><span style='color:#A50'>[r]</span></b> brd <b><span style='color:#A50'>192.168.1.255</span></b> <b><span style='color:#A50'>[e]</span></b> scope global dynamic wlp3s0
       valid_lft <b><span style='color:#A50'>40162</span></b> <b><span style='color:#A50'>[wj]</span></b>sec preferred_lft <b><span style='color:#A50'>40162</span></b> <b><span style='color:#A50'>[wj]</span></b>sec
    inet6 fe80::7a31:c1ff:fed5:40ce/64 scope link tentative dadfailed
       valid_lft forever preferred_lft forever
3: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc noqueue state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 46:06:f6:15:ea:fb brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>10.0.3.1</span></b> <b><span style='color:#A50'>[wt]/24</span></b> <b><span style='color:#A50'>[r]</span></b> brd <b><span style='color:#A50'>10.0.3.255</span></b> <b><span style='color:#A50'>[wr]</span></b> scope global br0
       valid_lft forever preferred_lft forever
4: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc fq_codel state UP group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet <b><span style='color:#A50'>10.0.1.1</span></b> <b><span style='color:#A50'>[we]/24</span></b> <b><span style='color:#A50'>[r]</span></b> brd <b><span style='color:#A50'>10.0.1.255</span></b> <b><span style='color:#A50'>[ww]</span></b> scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet6 fe80::800:27ff:fe00:0/64 scope link
       valid_lft forever preferred_lft forever
5: vboxnet1: <BROADCAST,MULTICAST> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc noop state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 0a:00:27:00:00:01 brd ff:ff:ff:ff:ff:ff
6: vboxnet2: <BROADCAST,MULTICAST> mtu <b><span style='color:#A50'>1500</span></b> <b><span style='color:#A50'>[l]</span></b> qdisc noop state DOWN group default qlen <b><span style='color:#A50'>1000</span></b> <b><span style='color:#A50'>[k]
</span></b>   <b><span style='color:#A50'> link/ether</span></b> <b><span style='color:#A50'>[j]</span></b> 0a:00:27:00:00:02 brd ff:ff:ff:ff:ff:ffsh: 1: 3: Bad file descriptor
</pre>

### CODE REVIEW

**Comment by sunaku** [comment]
The tests are currently brittle because they rely too much on the hard-coded labels inside the hinter. :scream:

 We should make hint labels configurable so that (1) a reduced set can be specified in tests and (2) so that the user can change the hint label sequence to suit their own tastes. :baby_symbol: 

For example, I would prefer [vim-sneak's sequence](https://github.com/justinmk/vim-sneak/blob/master/doc/sneak.txt#L389) over whatever this plugin currently provides. :open_mouth:  I would also take that a step further by choosing to use [a Dvorak-friendly sequence](https://github.com/sunaku/.vim/blob/dvorak/bundle/search/sneak.vim#L3-L6). :neckbeard:

**Comment by fcsonline** [comment]
I was thinking of implementing the same thing in tmux-fingers months ago! :+1: Thanks @sunaku

**Comment by Morantron** [comment]
Thanks again @sunaku , wonderful patch! :tada: You've managed to dig into the dark insides of `hinter.awk` without getting hurt! :trollface:

I agree that they are brittle, but since default hints do not change that often, they are usually good enough :tm:

About the seemingly nonsensical jumble of hints: they do have some sense! I've created [an issue](https://github.com/Morantron/tmux-fingers/issues/16) where I go in full detail about why they are like that.

Thanks again! This PR has been released in 0.3.2 version

**Comment by sunaku** [comment]
:triumph: :sparkles: :sunglasses: :+1:

**Pull request merged**
