### PR TITLE
Ruby rewrite

### PR DESCRIPTION
**Pull request by Morantron**

### CODE REVIEW

**Comment by andresgutgon** [comment]
You got this 💪

**Comment by Morantron** [comment]
I've accidentally rewritten the plugin in Crystal.

**Comment by andresgutgon** [comment]
> I've accidentally rewritten the plugin in Crystal.

Where do you have the Crystal version? No that I'm going to use (because I'm a happy customer of [tmux-thumbs](https://github.com/fcsonline/tmux-thumbs)) but I would like to see it

**Comment by Morantron** [comment]
> Where do you have the Crystal version?

It's just here in this repo.

> I'm a happy customer of [tmux-thumbs](https://github.com/fcsonline/tmux-thumbs)

Think about it: are you really happy?

**Comment by andresgutgon** [comment]
> It's just here in this repo.

I meant the refactor. I didn't found a PR with it or commit.

> Think about it: are you really happy?

I'll think about it. Do you do discounts?

**Comment by Morantron** [comment]
> I meant the refactor. I didn't found a PR with it or commit.

I just yoloed it into the main branch. It's a series of commits, the first one [here](https://github.com/Morantron/tmux-fingers/commit/c926a0eb4c4838e3b007f4c81b19bcc1a4fe2e73). But it's probably better to just check the current code rather than diffs.

> I'll think about it. Do you do discounts?

I will pay you 50EUR in cash if you stop using tmux-thumbs

**Comment by fcsonline** [comment]
This is the only way this project can win tmux-thumbs, increasing their CAC

**Comment by Morantron** [comment]
tmux-thumbs _is_ CACA

**Pull request closed without merging**
