### PR TITLE
Multiple Custom Commands

### PR DESCRIPTION
**Pull request by eyalfir**
Allow customizing multiple addition commands.
toggle chosen command with "C" when in the fingers pane.
Allow user to control the name of the command, the command to execute, and the style of how the chosen command in displayed.

This is my settings, for example:
```
set -g @fingers-commands "OPEN|xargs open|fg=white,bg=red;EDIT|xargs tmux new-window vim"
```

### CODE REVIEW

**Comment by eyalfir** [comment]
By the way - an extremely useful and time saving plugin. Kudus.

**Comment by Morantron** [comment]
Hi! Thanks for the PR :raised_hands:

I'll take a look into it once I have some bandwidth :pray:

**Comment by 0xC0FFEE** [comment]
I really like the idea and think this can be a huge improvement to this (already super awesome) plugin :tada:

For my personal workflow it'd make sense to decide which command to execute beforehand. This stems from my thought process: I know what I want to do (action) and then search for this (fingers mode). The current implementation of this feature forces me to work the other way around: search for what I need (fingers mode) and then specify the desired action (choose command).

Choosing the desired action before hand has also the huge advantage that it's possible to define different `@fingers-patterns` for different commands. For example an open-command does not need to take into account numbers.

**Comment by Morantron** [comment]
You can now define multiple commands with https://github.com/Morantron/tmux-fingers#fingers-copy-command-uppercase This command triggers when you hold SHIFT while typing the hint

**Pull request closed without merging**
